#!/usr/bin/env node

// Builds the Worker modules embedded by `workerd/config.capnp`.
//
// Usage:
//   pnpm install
//   node scripts/workerd/build.ts
//
// The command recreates `workerd/dist/`, prepares generated source files and frontend assets, then
// asks Wrangler for the same dry-run bundles it would deploy. The generated `modules.capnp` exposes
// one `<camelCasePackageName>Modules` constant per deployable package for the checked-in config.

import { execFileSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, posix, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { collectModules, type CollectedModule, type ModuleType } from "../release/hash-lib.ts";
import { readDeployablePackages } from "../release/manifest-lib.ts";
import { pnpmCommand } from "../pnpm-command.ts";
import { vpRunEnv } from "../vp/concurrency.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const PACKAGES_DIR = join(ROOT, "packages");
const WORKERD_DIR = join(ROOT, "workerd");
const DIST_DIR = join(WORKERD_DIR, "dist");
const BUNDLES_DIR = join(DIST_DIR, "bundles");
const STATE_DIR = join(WORKERD_DIR, "state");

const CAPNP_MODULE_FIELD = {
  esm: "esModule",
  text: "text",
  wasm: "wasm",
  data: "data",
} as const satisfies Record<ModuleType, string>;

function run(command: string, args: string[], cwd = ROOT, env = process.env): void {
  console.log(`> ${command} ${args.join(" ")}`);
  execFileSync(command, args, { cwd, env, stdio: "inherit" });
}

function runPnpm(args: string[], cwd = ROOT, env = process.env): void {
  const [command, commandArgs] = pnpmCommand(args, env);
  run(command, commandArgs, cwd, env);
}

function preparePrerequisites(): void {
  const env = vpRunEnv();

  // Runtime imports and every source-generated module that Wrangler's package-local build commands
  // expect to find. These mirror the focused preflight used by `pnpm run-local`, but use production
  // app/configurator builds because these bundles are intended for a standalone server.
  runPnpm(["exec", "vp", "run", "--cache", "@gadgets/typed-storage#build"], ROOT, env);
  run(process.execPath,
      [join(PACKAGES_DIR, "workshop-backend", "scripts", "build-format-blueprints.ts")],
      join(PACKAGES_DIR, "workshop-backend"));
  runPnpm(["exec", "vp", "run", "-r", "--cache", "build:configurator"], ROOT, env);
  runPnpm(["exec", "vp", "run", "-r", "--cache", "build:app"], ROOT, env);
  runPnpm(
      ["exec", "vp", "run", "--cache", "@gadgets/workshop-frontend#build:assets"], ROOT, env);
}

function capnpConstantName(packageName: string): string {
  return packageName.replace(/-([a-z0-9])/g, (_match, character: string) =>
    character.toUpperCase()) + "Modules";
}

function capnpString(value: string): string {
  return JSON.stringify(value);
}

function moduleDeclaration(packageName: string, module: CollectedModule): string {
  const field = CAPNP_MODULE_FIELD[module.type];
  const embeddedPath = posix.join("bundles", packageName, module.name);
  return `  (name = ${capnpString(module.name)}, ${field} = embed ${capnpString(embeddedPath)})`;
}

function generateModulesCapnp(
  bundles: { packageName: string; mainModule: string; modules: CollectedModule[] }[],
): string {
  const declarations = bundles.map(({ packageName, mainModule, modules }) => {
    const mainModuleEntry = modules.find((module) => module.name === mainModule);
    if (!mainModuleEntry) {
      throw new Error(`main module ${mainModule} is missing from ${packageName}`);
    }

    const orderedModules = [
      mainModuleEntry,
      ...modules.filter((module) => module !== mainModuleEntry),
    ];
    const entries = orderedModules.map((module) => moduleDeclaration(packageName, module));
    return `const ${capnpConstantName(packageName)} :List(Workerd.Worker.Module) = [\n` +
        `${entries.join(",\n")}\n];`;
  });

  return [
    "# Generated by `node scripts/workerd/build.ts`; do not edit.",
    "@0xbfdaf7cfe818fa42;",
    "",
    'using Workerd = import "/workerd/workerd.capnp";',
    "",
    ...declarations.flatMap((declaration) => [declaration, ""]),
  ].join("\n");
}

function main(): void {
  if (process.argv.length > 2) {
    throw new Error("usage: node scripts/workerd/build.ts");
  }

  preparePrerequisites();

  rmSync(DIST_DIR, { recursive: true, force: true });
  mkdirSync(BUNDLES_DIR, { recursive: true });
  mkdirSync(join(STATE_DIR, "durable-objects"), { recursive: true });
  mkdirSync(join(STATE_DIR, "objects"), { recursive: true });

  const bundles = readDeployablePackages(PACKAGES_DIR).map((pkg) => {
    const outDir = join(BUNDLES_DIR, pkg.name);
    runPnpm(
        ["exec", "wrangler", "deploy", "--dry-run", "--outdir", outDir], pkg.dir);
    const bundle = collectModules(outDir);
    return { packageName: pkg.name, ...bundle };
  });

  const modulesPath = join(DIST_DIR, "modules.capnp");
  writeFileSync(modulesPath, generateModulesCapnp(bundles));
  console.log(`\nBuilt ${bundles.length} Worker bundles and ${modulesPath}.`);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
